name: The Institute for Bodymind Integration
favicon: null
layout_spectrum: 1
typography_spectrum: 0.11679900530725718
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#4c4c4c'
    - '#b4b4b4'
    - '#8e8e8e'
  brandStrength: 0.3852868571411818
  lightness: 0.334850100800395
  saturation: 0.6180555967148393
  rhythmicContrast: 0.5746836753096431
purpose: []
