name: The Institute for Bodymind Integration
favicon: null
layout_spectrum: 0.9594489072915167
typography_spectrum: 0.11679900530725718
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.3852868571411818
  lightness: 0.334850100800395
  saturation: 0.6180555967148393
  rhythmicContrast: 0.5746836753096431
purpose: []
